# All Access Artist - Cloudflare Worker Configuration
# Version 2.0.0 - Proprietary

name = "allaccessartist"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

# Environment variables (will be set in Cloudflare dashboard)
[vars]
# SUPABASE_URL will be set in dashboard
# SUPABASE_SERVICE_KEY will be set in dashboard
# SUPABASE_ANON_KEY will be set in dashboard
# SUPABASE_JWT_SECRET will be set in dashboard

# Production environment
[env.production]
name = "allaccessartist"

# Staging environment
[env.staging]
name = "allaccessartist-staging"

# Development environment  
[env.development]
name = "allaccessartist-dev"
